# fly.toml app configuration file generated for contacttracker9000-bold-glade-5099 on 2024-08-07T10:47:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contacttracker9000-bold-glade-5099'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
